### ISSUE TITLE
Some exceptions during effects handling crash the server

### ISSUE THREAD

**Issue by phjardas** [phjardas/tabidisco#8]
Examples:

* No token found when pressing the `play` button.
* No token found when uploading a song.
* Insufficient file permissions when modifying the songs database.

**Comment by phjardas** [comment]
Here's a log excerpt when trying to upload a song without a token:

```
[request] [set_song #16]
[request] [read_token #17]
[action] [set_song] {"id":"16","timestamp":"2018-03-07T15:31:13.707Z","type":"set_song","private":"jPu4UnlYj-PQXA9HAAAB","payload":{"filename":"08 California Love.mp3"}}
[event] [action] {"type":"action","action":{"id":"16","timestamp":"2018-03-07T15:31:13.707Z","type":"set_song","private":"jPu4UnlYj-PQXA9HAAAB","payload":{"filename":"08 California Love.mp3"}},"id":"16","timestamp":"2018-03-07T15:31:13.738Z"}
[action] [read_token] {"id":"17","timestamp":"2018-03-07T15:31:13.738Z","type":"read_token"}
[event] [action] {"type":"action","action":{"id":"17","timestamp":"2018-03-07T15:31:13.738Z","type":"read_token"},"id":"17","timestamp":"2018-03-07T15:31:13.738Z"}
[action] [read_token.error] {"id":"18","timestamp":"2018-03-07T15:31:13.940Z","type":"read_token.error","replyTo":"17","error":{"message":"No token found"}}
[request] [read_token #17] reply error: Error: No token found
    at Timeout.setTimeout (/home/phjardas/workspace/tabidisco/server/src/lib/pi/mock.ts:34:21)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[event] [action] {"type":"action","action":{"id":"18","timestamp":"2018-03-07T15:31:13.940Z","type":"read_token.error","replyTo":"17","error":{"message":"No token found"}},"id":"20","timestamp":"2018-03-07T15:31:13.950Z"}
[action] [set_song.error] {"id":"19","timestamp":"2018-03-07T15:31:13.950Z","type":"set_song.error","private":"jPu4UnlYj-PQXA9HAAAB","replyTo":"16","error":{"message":"request failed: Error: No token found"}}
[request] [set_song #16] reply error: Error: request failed: Error: No token found
    at Object.next (/home/phjardas/workspace/tabidisco/server/src/lib/bus.ts:115:23)
    at SafeSubscriber.__tryOrUnsub (/home/phjardas/workspace/tabidisco/server/node_modules/src/Subscriber.ts:255:10)
    at SafeSubscriber.next (/home/phjardas/workspace/tabidisco/server/node_modules/src/Subscriber.ts:205:14)
    at Subscriber._next (/home/phjardas/workspace/tabidisco/server/node_modules/src/Subscriber.ts:136:22)
    at Subscriber.next (/home/phjardas/workspace/tabidisco/server/node_modules/src/Subscriber.ts:96:12)
    at FirstSubscriber._emitFinal (/home/phjardas/workspace/tabidisco/server/node_modules/src/operators/first.ts:151:19)
    at FirstSubscriber._emit (/home/phjardas/workspace/tabidisco/server/node_modules/src/operators/first.ts:133:10)
    at FirstSubscriber._tryPredicate (/home/phjardas/workspace/tabidisco/server/node_modules/src/operators/first.ts:124:12)
    at FirstSubscriber._next (/home/phjardas/workspace/tabidisco/server/node_modules/src/operators/first.ts:109:12)
    at FirstSubscriber.Subscriber.next (/home/phjardas/workspace/tabidisco/server/node_modules/src/Subscriber.ts:96:12)

/home/phjardas/workspace/tabidisco/server/src/lib/bus.ts:115
            obs.error(new Error('request failed: ' + error));
                      ^
Error: request failed: Error: request failed: Error: No token found
    at Object.next (/home/phjardas/workspace/tabidisco/server/src/lib/bus.ts:115:23)
    at SafeSubscriber.__tryOrUnsub (/home/phjardas/workspace/tabidisco/server/node_modules/src/Subscriber.ts:255:10)
    at SafeSubscriber.next (/home/phjardas/workspace/tabidisco/server/node_modules/src/Subscriber.ts:205:14)
    at Subscriber._next (/home/phjardas/workspace/tabidisco/server/node_modules/src/Subscriber.ts:136:22)
    at Subscriber.next (/home/phjardas/workspace/tabidisco/server/node_modules/src/Subscriber.ts:96:12)
    at FirstSubscriber._emitFinal (/home/phjardas/workspace/tabidisco/server/node_modules/src/operators/first.ts:151:19)
    at FirstSubscriber._emit (/home/phjardas/workspace/tabidisco/server/node_modules/src/operators/first.ts:133:10)
    at FirstSubscriber._tryPredicate (/home/phjardas/workspace/tabidisco/server/node_modules/src/operators/first.ts:124:12)
    at FirstSubscriber._next (/home/phjardas/workspace/tabidisco/server/node_modules/src/operators/first.ts:109:12)
    at FirstSubscriber.Subscriber.next (/home/phjardas/workspace/tabidisco/server/node_modules/src/Subscriber.ts:96:12)
[nodemon] app crashed - waiting for file changes before starting...
```
